### ISSUE TITLE
 0.0.10 dev files have wrong capitalization for ArducamTOFCamera

### ISSUE THREAD

**Issue by flipphillips** [ArduCAM/arducam_ppa#12]
My machine updated to the 0.0.10 dev files today. Trying to rebuild a project from the `examples` folder results in complaints that `ArduCamTOFCamera.h` and `.hpp` can't be found.

A quick look @ the `dpkg` shows that the files have been named `ArducamTOFCamera`.

<img width="258" alt="Screenshot 2023-01-11 at 3 55 29 PM" src="https://user-images.githubusercontent.com/671183/211916441-cab0ab01-f551-42f3-a823-0097dc111118.png">

Furthermore, just re-linking the files to the camel case name shows that there are various things broken or missing (`FrameBuffer`  in the C example, for example)

**Comment by dennis-ard** [comment]
Sorry for the inconvenience, I renamed ArduCam to Arducam, you can refer to the warehouse of [Arducam_TOF_Camera](https://github.com/ArduCAM/Arducam_tof_camera),
